### ISSUE TITLE
Add way to turn off or disable

### ISSUE THREAD

**Issue by Civitello** [NearW/minecraft-speedrun#6] opened 2021-05-09 02:04 UTC
When doing a long run (AA) sometimes stopping the server is required. It is important to be able to stop the server without activating this.

**Comment by NearW** [comment] 2021-05-09 13:33
I don't really understand what feature is requested here.

Is this a duplicate of #4?

**Comment by Civitello** [comment] 2021-05-09 13:55
Maybe I don't understand how this works. It is my understanding that minecraft-speedrun will automatically do its things whenever the server stops, I need to be able to easily prevent it from doing anything (like in the event of a crash) after we decide to run a seed and are not going to reset.

**Comment by NearW** [comment] 2021-05-09 14:36
I understand. I'll probably add an AA setting for this. 

Accepted.

**Comment by NearW** [comment] 2021-05-09 16:50
@PhoneticFaulure https://github.com/NearW/minecraft-speedrun/commit/9460ffe32c902858ec414b9339df59c236037b1a

Please check the [README](https://github.com/NearW/minecraft-speedrun#readme). I added a new section on how to use this script when running AA. Is that sufficient?

**Closed as completed** 2021-06-05 21:06 UTC
Labels: enhancement
